# Installation of Python 2.7

FROM whatever # Replaced by CAMP during realization

RUN apt-get install -y --no-install-recommends python2.7 \
    && rm -rf  /usr/bin/python \
    && ln -s /usr/bin/python2.7 /usr/bin/python 
