#
# CAMP
#
# Copyright (C) 2017, 2018 SINTEF Digital
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

language: python

python:
  - "2.7"
  - "3.5"

env:
  global:
    - NAME="camp"
  matrix:
    - Z3_VERSION="4.8.4.d6df51951f4c" Z3_PLATFORM="x64-debian-8.11" PUBLISH="true"
    - Z3_VERSION="4.7.1" Z3_PLATFORM="x64-debian-8.10"
    - Z3_VERSION="4.6.0" Z3_PLATFORM="x64-debian-8.10"


dist: xenial
sudo: required

services:
  - docker

before_install:
  - pip install codacy-coverage

install:
  - |
    docker build --no-cache \
                 --build-arg PYTHON_VERSION=${TRAVIS_PYTHON_VERSION} \
                 --build-arg WITH_TESTS=--camp-with-tests \
                 --build-arg Z3_VERSION=${Z3_VERSION} \
                 --build-arg Z3_PLATFORM=${Z3_PLATFORM} \
                 -t ${DOCKER_USERNAME}/${NAME}:dev .

script:
  - |
    docker run --name tests \
               -v /var/run/docker.sock:/var/run/docker.sock \
               -t ${DOCKER_USERNAME}/${NAME}:dev \
               /bin/bash -c "green -qrfvv -s 1 tests ; coverage xml"
  - docker cp tests:/camp/.coverage.xml .coverage.xml
  - python-codacy-coverage -r coverage.xml

after_success:
  - |  
    if [[ ! -z "${PUBLISH}" && "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PYTHON_VERSION}" == "3.5" ]]
    then
       docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
       docker push ${DOCKER_USERNAME}/${NAME}:dev
       echo ${TRAVIS_TAG}
       if [[ "${TRAVIS_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
       then
          docker tag ${DOCKER_USERNAME}/${NAME}:dev ${DOCKER_USERNAME}/${NAME}:${TRAVIS_TAG} 
          docker tag ${DOCKER_USERNAME}/${NAME}:dev ${DOCKER_USERNAME}/${NAME}:latest 
          docker push ${DOCKER_USERNAME}/${NAME}
      fi
    fi
