#
# CAMP
#
# Copyright (C) 2017, 2018 SINTEF Digital
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

language: python

python:
  - "2.7"

env:
  global:
    - NAME="camp"
  
services:
  - docker
  
install:
  - docker build -t $DOCKER_USERNAME/$NAME:dev .

script:
  - python setup.py test -s tests.entities test -s tests.codecs
  - docker run -it $DOCKER_USERNAME/$NAME:dev python setup.py test -s tests.generate
  - python setup.py test -s tests.realize
  - python setup.py test -s tests.execute

after_success:
  - |
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push $DOCKER_USERNAME/$NAME:dev
    echo $TRAVIS_TAG
    if [[ "$TRAVIS_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      docker tag $DOCKER_USERNAME/$NAME:dev $DOCKER_USERNAME/$NAME:$TRAVIS_TAG ;
      docker tag $DOCKER_USERNAME/$NAME:dev $DOCKER_USERNAME/$NAME:latest ;
      docker push $DOCKER_USERNAME/$NAME;
    fi
