#
# CAMP
#
# Copyright (C) 2017, 2018 SINTEF Digital
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

language: python

python:
  - "2.7"

env:
  global:
    - NAME="camp"
    - CODECOV_TOKEN="6dfaf6b6-29f5-4816-8ace-908bbbb7e01e"

dist: xenial
sudo: required

services:
  - docker

before_install:
  - pip install codecov coverage
  
install:
  # Install CAMP and its dependencies 
  - python -c 'import sys; print(sys.path)'
  - sudo bash install.sh --debug --camp-from-sources --camp-with-tests --install-z3 --z3-python-bindings /opt/python/2.7.15/lib/python2.7

script:
  - green -qrf -vv tests
  - codecov

after_success:
  - |
    docker build -t $DOCKER_USERNAME/$NAME:dev .;
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    docker push $DOCKER_USERNAME/$NAME:dev;
    echo $TRAVIS_TAG;
    if [[ "$TRAVIS_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      docker tag $DOCKER_USERNAME/$NAME:dev $DOCKER_USERNAME/$NAME:$TRAVIS_TAG ;
      docker tag $DOCKER_USERNAME/$NAME:dev $DOCKER_USERNAME/$NAME:latest ;
      docker push $DOCKER_USERNAME/$NAME;
    fi
