version: '3'

services:

  registry:
    build: ./registry
    command: ruby app/app.rb -h registry-db
    expose:
      - "4567"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
