kind: Service
apiVersion: v1
metadata:
  name: actions
  labels:
    domain: tellucloud
    app: actions
    type: core
spec:
  selector:
    app: actions
  ports:
    - name: metrics
      port: 9090
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: actions
  labels:
    domain: tellucloud
    app: actions
    type: core
spec:
  replicas: 1 #CAMP
  selector:
    matchLabels:
      app: actions
  template:
    metadata:
      labels:
        domain: tellucloud
        app: actions
        type: core
    spec:
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: config
        configMap:
          name: actions
      containers:
      - name: actions
        image: tellu/actions:latest
        terminationMessagePath: /logs/termination/actions.log
        terminationMessagePolicy: File
        env:
        - name: CONFIGDIR
          value: "/config"
        - name: LOGDIR
          value: "/logs"
        - name: SERVICE_NAME
          value: actions
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxMetaspaceSize=300m -XX:MaxHeapSize=100m" #CAMP
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 200m #CAMP limits:cpu
            memory: 500Mi #CAMP limits:memory
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: logs
          mountPath: /logs
        - name: config
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /service/health
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10 # default
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /service/health
            port: 9090
          initialDelaySeconds: 60
          timeoutSeconds: 2
