// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.stamp.camp.samples.testman.domain;

import eu.stamp.camp.samples.testman.domain.TCExecution;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TCExecution_Roo_Configurable {
    
    declare @type: TCExecution: @Configurable;
    
}
