services:
  be:
    depends_on:
    - esb
    - mysql
    environment:
    - ESBHOST=supersede-esb
    image: supersede/be
    ports:
    - 8081:8081
  esb:
    container_name: supersede-esb
    image: supersede/esb
    ports:
    - 9443:9443
    - 8280:8280
  mysql:
    container_name: supersede-mysql
    image: supersede/mysql
version: '2'
