# Each service defined here deploy CityGo platform
# This docker-compose file deploy the platfomr using Apache Server.
#
# Maintainer: Fernando Méndez Requena - fernando.mendez@atos.net


version: '2'

services:
  db:
    build: ../Citygo/Postgres
    container_name: my_postgres
    networks:
      - my-app-bridge
    environment:
      - max_connections=500
      - shared_buffers=256
      - port=5432
      - POSTGRES_DB=citygo_malaga
      - POSTGRES_USER=citygo
      - POSTGRES_PASSWORD=5X6sdoq0!?az=v2aSX
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: ../Citygo
    container_name: my_web
    networks:
      - my-app-bridge
    environment:
      - StartServers=2
      - MinSpareThreads=25
      - MaxSpareThreads=75
      - ThreadLimit=64
      - ThreadsPerChild=25
      - MaxRequestWorkers=150
      - MaxConnectionsPerChild=0
      - BROWSERNAME=chrome
      - PLATFORM=LINUX
      - JAVASCRIPTENABLED=True
      - MAXINSTANCES=50
      - CSSSELECTORSENABLED=True
      - BROWSERCONNECTIONENABLED=True
    volumes: 
      - ../Citygo/www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      - mongo
    expose: 
      - "80"

  hub:
    container_name: "selenium_hub"
    image: selenium/hub
    volumes:
      - /dev/shm:/dev/shm/
    networks:
      - my-app-bridge
    ports:
      - "4444:4444"

  selenium_chrome:
    container_name: selenium_chrome
    image: selenium/node-chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    depends_on:
      - hub
    networks:
      - my-app-bridge

  mongo:
    container_name: "my_mongo"
    image: mongo:4.0.6-xenial
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - my-app-bridge

volumes:
  postgres_data:

networks:
  my-app-bridge:
    driver: bridge
