version: '2'

services:
  db:
    build: ../repo/Postgres
    container_name: my_postgres
    image: postgres:ubuntu-latest
    environment:
      - max_connections=500
      - shared_buffers=256
      - port=5432
      - POSTGRES_DB=citygo_malaga
      - POSTGRES_USER=citygo
      - POSTGRES_PASSWORD=5X6sdoq0!?az=v2aSX
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    build: ../repo/Showcase
    image: showcase:python-2.7
    container_name: my_web
    environment:
      - StartServers=2
      - MinSpareThreads=25
      - MaxSpareThreads=75
      - ThreadLimit=64
      - ThreadsPerChild=25
      - MaxRequestWorkers=150
      - MaxConnectionsPerChild=0
    volumes: 
      - ../build/showcase--python-2.7/www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      - orion
  mongo:
    image: mongo:3.2
    command: --nojournal
    ports:
      - "27017:27017"
    expose:
      - "27017"
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
    expose:
      - "1026"
    depends_on:
      - mongo
  
  cygnus-common:
    image: fiware/cygnus-common
    container_name: cygnus-common
    environment:
      - CYGNUS_LOG_LEVEL=DEBUG
      - CYGNUS_SERVICE_PORT=5050
      - CYGNUS_API_PORT=8081
      - CYGNUS_MYSQL_PORT=3306
      - MVN_VER=3.5.2
      - FLUME_VER=1.4.0
      - JAVA_VERSION=1.8.0
      - CYGNUS_USER=cygnus
      
    expose:
      - "8081"

  cygnus-ngsi:
    image: fiware/cygnus-ngsi
    container_name: cygnus-ngsi
    environment:
      - CYGNUS_CARTO_USER=jcarneroatos
      - CYGNUS_CARTO_KEY=16460edcecd5b634367a5b5eae65708654d260b3
      - CYGNUS_LOG_LEVEL=DEBUG
      - CYGNUS_SERVICE_PORT=5050
      - CYGNUS_API_PORT=8081
      - CYGNUS_MYSQL_PORT=3306
      - MVN_VER=3.5.2
      - FLUME_VER=1.4.0
      - JAVA_VERSION=1.8.0
      - CYGNUS_USER=cygnus
    expose:
      - "8081"

volumes:
  db_data:
    external: true
