services:
  apache:
    container_name: my_apache
    environment:
    - StartServers=2
    - MinSpareThreads=25
    - MaxSpareThreads=75
    - ThreadLimit=64
    - ThreadsPerChild=25
    - MaxRequestWorkers=150
    - MaxConnectionsPerChild=0
    - MinSpareServers=5
    - MaxSpareServers=10
    image: apache:none-ubuntu-latest
  db:
    container_name: my_db
    depends_on:
    - apache
    - web
    environment:
    - max_connections=500
    - shared_buffers=256
    - port=5432
    - POSTGRES_DB=------------------
    - POSTGRES_USER=---------------------
    - POSTGRES_PASSWORD=-------------------
    - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
    - '5432'
    image: postgres:showcaseserver-ubuntu-latest
    ports:
    - 5432:5432
  web:
    command: python /webapp/ShowcaseServer/manage.py runserver 0.0.0.0:8000
    container_name: my_web
    depends_on:
    - db
    - apache
    environment:
    - PYTHONUSERBASE=.webapp/ShowcaseServer/
    image: postgres:showcaseserver-ubuntu-latest
    ports:
    - 8000:8000
    volumes:
    - ./webapp:/webapp
version: '2'
volumes:
  db_data:
    external: true
