#
# CAMP
#
# Copyright (C) 2017 -- 2019 SINTEF Digital
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#

FROM debian:stretch

RUN apt-get -y update \
        && apt-get -y upgrade \
        && apt-get -y install openjdk-8-jre


