

version: '2.1'

services:

  springpetclinic:
    build: ./springpetclinicMS
    ports:
      - "8080:8080"
    restart: always
    links:
      - database
    depends_on:
      - database

  database:
    build: ./mysqldb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    restart: always
