# version 3 causes some issues. We use 2 instead
version: '2'

services:
  proactive:
    build: ./proactive
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always

  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pouet123
    restart: always
