version: '3'

services:

  proactive:
    build: ./proactive
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build: ./database
    expose:
      - 3306
      - 5432
    environment:
      - MYSQL_ROOT_PASSWORD=pouet123
      - POSTGRES_PASSWORD=pouet123
