version: '3'

services:

  lutece:
    build: ./lutece
    ports:
      - "8080:8080"
    depends_on:
      - storage

  storage:
    build: ./mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=motdepasse
