title: CAMP
description: >-
  Amplify your testing with more configurations!
url: https://stamp-project.github.io/
baseurl: /camp

theme: jekyll-theme-minimal

exclude:
 - README.md
 - Gemfile.lock
 - Gemfile
